# Imports & Setup

In [42]:
import sys
from pathlib import Path

base_dir = Path().resolve().parent
sys.path.append(base_dir)

from scripts.sales_data import SalesData
from scripts.utils import line_plot, bar_plot, scatter_plot, pie_chart, save_plot

# Data Loading & Cleaning

In [110]:
file_path = Path(base_dir) / "data/raw/Walmart_Sales.csv"

try:
    sales_data = SalesData(file_path)
    sales_data.load_data().clean_data()
    df = sales_data.df
except Exception as e:
    print(f"Error: {e}")

Error: 'DataFrame' object has no attribute 'clean_data'

# Exploratory Data

In [111]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Month,Week
0,1,2010-05-02,1643690.90,0,42.31,2.572,211.096358,8.106,5,17
1,1,2010-12-02,1641957.44,1,38.51,2.548,211.242170,8.106,12,48
4,1,2010-05-03,1554806.68,0,46.50,2.625,211.350143,8.106,5,18
5,1,2010-12-03,1439541.59,0,57.79,2.667,211.380643,8.106,12,48
8,1,2010-02-04,1594968.28,0,62.27,2.719,210.820450,7.808,2,5

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2565 entries, 0 to 6432
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         2565 non-null   int64
 1   Date          2565 non-null   datetime64[ns]
 2   Weekly_Sales  2565 non-null   float64
 3   Holiday_Flag  2565 non-null   int64
 4   Temperature   2565 non-null   float64
 5   Fuel_Price    2565 non-null   float64
 6   CPI           2565 non-null   float64
 7   Unemployment  2565 non-null   float64
 8   Month         2565 non-null   int32
 9   Week          2565 non-null   UInt32
dtypes: UInt32(1), datetime64[ns](1), float64(5), int32(1), int64(2)
memory usage: 202.9 KB

In [113]:
df.describe()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Month,Week
count,2565.000000,2565,2.565000e+03,2565.000000,2565.000000,2565.000000,2565.000000,2565.000000,2565.000000,2565.0
mean,23.000000,2011-05-29 11:47:22.105263104,1.059872e+06,0.105263,59.585864,3.329579,171.386349,8.022267,6.561404,25.157895
min,1.000000,2010-01-10 00:00:00,2.099862e+05,0.000000,-2.060000,2.513000,126.085452,3.879000,1.000000,1.0
25%,12.000000,2010-10-09 00:00:00,5.700695e+05,0.000000,45.260000,2.868000,131.586613,6.908000,4.000000,13.0
50%,23.000000,2011-05-08 00:00:00,9.813452e+05,0.000000,61.100000,3.417000,182.598306,7.907000,6.000000,23.0
75%,34.000000,2012-02-03 00:00:00,1.450733e+06,0.000000,74.570000,3.702000,212.512605,8.622000,10.000000,40.0
max,45.000000,2012-12-10 00:00:00,2.752122e+06,1.000000,100.070000,4.468000,227.169392,14.313000,12.000000,50.0
std,12.989706,NaN,5.573831e+05,0.306952,19.069276,0.461985,39.293112,1.878158,3.459797,15.108178

In [114]:
df.shape

(2565, 10)

In [115]:
df.size

25650

In [116]:
df.index

Index([   0,    1,    4,    5,    8,    9,   13,   17,   18,   21,
       ...
       6409, 6410, 6413, 6414, 6418, 6422, 6423, 6427, 6431, 6432],
      dtype='int64', length=2565)

In [117]:
df.columns

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment', 'Month', 'Week'],
      dtype='object')

In [118]:
df.dtypes

Store                    int64
Date            datetime64[ns]
Weekly_Sales           float64
Holiday_Flag             int64
Temperature            float64
Fuel_Price             float64
CPI                    float64
Unemployment           float64
Month                    int32
Week                    UInt32
dtype: object

In [119]:
df.isnull().sum()

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
Month           0
Week            0
dtype: int64

In [120]:
df.duplicated().sum()

np.int64(0)

In [121]:
df.duplicated()

0       False
1       False
4       False
5       False
8       False
        ...
6422    False
6423    False
6427    False
6431    False
6432    False
Length: 2565, dtype: bool

In [122]:
df.isna().sum()

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
Month           0
Week            0
dtype: int64

# Save Cleaned Data

In [123]:
output_path = Path(base_dir) / "data/processed/Clean_Walmart_Sales.csv"
sales_data.save_clean_data(output_path)